name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['apps/server/**', '!**/*.md', '.github/workflows/deploy.yml']

jobs:
  deployment:
    environment:
      name: rideau-server-prod
      url: https://rideau.fly.dev
    name: Deploy Rideau Server to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config apps/server/fly.toml \
            --dockerfile apps/server/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
